import 'package:light_reader/feature/reader/model/book.dart';

Chapter _ch(int i, String title, List<String> paragraphs) {
  return Chapter(
    id: '$i',
    chapterTitle: title,
    paragraphs: paragraphs,
    bookName: 'The Wind in the Willows',
  );
}

/// Abridged public-domain retelling of Kenneth Grahame's The Wind in the Willows (1908).
final sampleBook6 = Book(
  id: 'wind-in-the-willows',
  title: 'The Wind in the Willows',
  author: 'Kenneth Grahame',
  chapters: [
    _ch(0, '1The River Bank', [
      'The Mole had been working very hard all the morning, spring-cleaning his little home. First with brooms, then with dusters; then on ladders and steps and chairs, with a brush and a pail of whitewash; till he had dust in his throat and eyes, and splashes of whitewash all over his black fur, and an aching back and weary arms.',
      'Spring was moving in the air above and in the earth below and around him, penetrating even his dark and lowly little house with its spirit of divine discontent and longing. It was small wonder, then, that he suddenly flung down his brush on the floor, said “Bother!” and “O blow!” and also “Hang spring-cleaning!” and bolted out of the house without even waiting to put on his coat.',
      'Something up above was calling him imperiously, and he made for the steep little tunnel which answered in his case to the gravelled carriage-drive owned by animals whose residences are nearer to the sun and air. So he scraped and scratched and scrabbled and scrooged, and then he scrooged again and scrabbled and scratched and scraped, working busily with his little paws and muttering to himself, “Up we go! Up we go!” till at last, pop! his snout came out into the sunlight, and he found himself rolling in the warm grass of a great meadow.',
      '“This is fine!” he said to himself. “This is better than whitewashing!” The sunshine struck hot on his fur, birds sang, the breeze was soft, and the world seemed full of a happy holiday feeling. He had not felt so restless, so much alive, in all the long winter underground.',
    ]),
    _ch(1, '2The Open World', [
      'Jumping off all his four legs at once, in the joy of living and the delight of spring without its cleaning, he pursued his way across the meadow till he reached the hedge on the further side. He thought his happiness was complete when, as he meandered aimlessly along, suddenly he stood by the edge of a full-fed river.',
      'Never in his life had he seen a river before—this sleek, sinuous, full-bodied animal, chasing and chuckling, gripping things with a gurgle and leaving them with a laugh, to fling itself on fresh playmates that shook themselves free, and were caught and held again. All was a-shake and a-shiver—glints and gleams and sparkles, rustle and swirl, chatter and bubble.',
      'The Mole was bewitched, entranced, fascinated. By the side of the river he trotted as one trots, when very small, by the side of a man who holds one spellbound by exciting stories; and when tired at last, he sat on the bank, while the river chattered on to him, a babbling procession of the best stories in the world, sent from the heart of the earth to be told at last to the insatiable sea.',
      'As he sat on the grass and looked across the river, a dark hole in the bank opposite, just above the water’s edge, caught his eye, and dreamily he fell to considering what a nice, snug dwelling-place it would make for an animal with few wants and fond of a bijou riverside residence, above flood level and remote from noise and dust.',
    ]),
    _ch(2, '3The Water Rat', [
      'As he gazed, something bright and small seemed to twinkle down in the heart of it, vanished, then twinkled once more like a tiny star. Then, as he looked, it winked at him, and so declared itself to be an eye; and a small face began gradually to grow up round it, like a frame round a picture. A brown little face, with whiskers. A grave round face, with the same twinkle in its eye that had first attracted his notice. Small neat ears and thick silky hair. It was the Water Rat!',
      'The two animals stood and regarded each other cautiously. “Hullo, Mole!” said the Water Rat. “Hullo, Rat!” said the Mole. “Would you like to come over?” enquired the Rat presently. “Oh, it’s all very well to talk,” said the Mole, rather pettishly, he being new to a river and riverside life and its ways.',
      'The Rat said nothing, but stooped and unfastened a rope and hauled on it; then lightly stepped into a little boat which the Mole had not observed. It was painted blue outside and white within, and was just the size for two animals; and the Mole’s whole heart went out to it at once, even though he did not yet fully understand its uses.',
      'The Rat rowed smartly across and made fast. Then he held up his forepaw as the Mole stepped gingerly down. “Lean on that!” he said. “Now then, step lively!” and the Mole to his surprise and rapture found himself actually seated in the stern of a real boat. “This has been a wonderful day!” said he, as the Rat shoved off. “Do you know, I’ve never been in a boat before in all my life.”',
    ]),
    _ch(3, '4Messing About in Boats', [
      '“What?” cried the Rat, open-mouthed. “Never been in a—you never—well I—what have you been doing, then?” “Is it so nice as all that?” asked the Mole shyly, though he was quite prepared to believe it as he leant back in his seat and surveyed the cushions, the oars, the rowlocks, and all the fascinating fittings, and felt the boat sway lightly under him.',
      '“Nice? It’s the only thing,” said the Water Rat solemnly, as he leant forward for his stroke. “Believe me, my young friend, there is nothing—absolute nothing—half so much worth doing as simply messing about in boats. Simply messing,” he went on dreamily: “messing—about—in—boats; messing—”',
      '“Look ahead, Rat!” cried the Mole suddenly. It was too late. The boat struck the bank full tilt. The dreamer, the joyous oarsman, lay on his back at the bottom of the boat, his heels in the air. “—about in boats—or with boats,” the Rat went on composedly, picking himself up with a pleasant laugh. “In or out of ’em, it doesn’t matter. Nothing seems really to matter, that’s the charm of it. Whether you get away, or whether you don’t; whether you arrive at your destination or whether you reach somewhere else, or whether you never get anywhere at all, you’re always busy, and you never do anything in particular; and when you’ve done it there’s always something else to do, and you can do it if you like, but you’d much better not.”',
      'The Mole waggled his toes from sheer excess of happiness. “What a day I’m having!” he said. “Let us start at once!” “Hold hard a minute, then!” said the Rat. He looped the painter through a ring in his landing-stage, climbed up into his hole above, and after a short interval reappeared staggering under a fat, wicker luncheon-basket.',
    ]),
    _ch(4, '5The Picnic', [
      '“Shove that under your feet,” he observed to the Mole, as he passed it down into the boat. Then he untied the painter and took the sculls again. “What’s inside it?” asked the Mole, wriggling with curiosity. “There’s cold chicken inside it,” replied the Rat briefly; “coldtonguecoldhamcoldbeefpickledgherkinssaladfrenchrollscresssandwichespottedmeatgingerbeerlemonadesodawater—”',
      '“O stop, stop,” cried the Mole in ecstasies: “This is too much!” “Do you really think so?” enquired the Rat seriously. “It’s only what I always take on these little excursions; and the other animals are always telling me that I’m a cheapskate and a miser and a mean beast, and I don’t give them enough. However, it won’t do to have our friends saying nasty things about us, and as we are both of us blessed with excellent appetites, we had better see what there is to be done.”',
      'They got the boat out into the current and then Rat let her drop quietly down, sculling, now and again, to keep her near the bank. The Mole trailed a paw in the water and dreamed long waking dreams. The Water Rat, like the good fellow he was, sculled steadily on and forbore to disturb him.',
      '“I like your clothes awfully, old chap,” he remarked after some half an hour or so had passed. “I’m going to get a black velvet smoking-suit myself some day, as soon as I can afford it.” “I beg your pardon,” said the Mole, pulling himself together with an effort. “You must think me very rude; but all this is so new to me. So—this—is—a—River!” “The River,” corrected the Rat. “And you really live by the river? What a jolly life!”',
    ]),
    _ch(5, '6River-Bankers', [
      '“By it and with it and on it and in it,” said the Rat. “It’s brother and sister to me, and aunts, and company, and food and drink, and (naturally) washing. It’s my world, and I don’t want any other. What it hasn’t got is not worth having, and what it doesn’t know is not worth knowing.”',
      '“But isn’t it a bit dull at times?” the Mole ventured to ask. “Just you and the river, and no one else to pass a word with?” “No one else to—well, I mustn’t be hard on you,” said the Rat with forbearance. “You’re new to it, and of course you don’t know. The bank is so crowded nowadays that many people are moving away altogether. O no, it isn’t what it used to be, at all. Otters, kingfishers, dabchicks, moorhens, all of them about all day long and always wanting you to do something—as if a fellow had no business of his own to attend to!”',
      '“What lies over there?” asked the Mole, waving a paw towards a background of woodland that darkly framed the water-meadows on one side of the river. “That? O, that’s just the Wild Wood,” said the Rat shortly. “We don’t go there very much, we river-bankers.” “Aren’t they—aren’t they very nice people in there?” said the Mole a trifle nervously.',
      '“W-e-ll,” replied the Rat, “let me see. The squirrels are all right. And the rabbits—some of ’em, but rabbits are a mixed lot. And then there’s Badger, of course. He lives right in the heart of it; wouldn’t live anywhere else, either, if you paid him to do it. Nobody interferes with him. They’d better not,” he added significantly.',
    ]),
    _ch(6, '7The Wild Wood', [
      '“Why, who should interfere with him?” asked the Mole. “Well, of course—there—are others,” explained the Rat in a hesitating sort of way. “Weasels—and stoats—and foxes—and so on. They’re all right in a way—I’m very good friends with them—pass the time of day when we meet, and all that—but they break out sometimes, there’s no denying it, and then—well, you can’t really trust them, and that’s the fact.”',
      'The Mole knew well that it is quite against animal-etiquette to dwell on possible trouble ahead, or even to allude to it; so he dropped the subject. “And beyond the Wild Wood again?” he asked: “Where it’s all blue and dim, and one sees what may be hills or perhaps they mayn’t, and something like the smoke of towns, or is it only cloud-drift?”',
      '“Beyond the Wild Wood comes the Wide World,” said the Rat. “And that’s something that doesn’t matter, either to you or me. I’ve never been there, and I’m never going, nor you either, if you’ve got any sense at all. Don’t ever refer to it again, please. Now then! Here’s our backwater at last, where we’re going to lunch.”',
      'Leaving the main stream, they now passed into what seemed at first sight like a little land-locked lake. Green turf sloped down to either edge, brown snaky tree-roots gleamed below the surface of the quiet water, while ahead of them the silvery shoulder and foamy tumble of a weir, arm-in-arm with a restless dripping mill-wheel, that held up in its turn a grey-gabled mill-house, filled the air with a soothing murmur of sound, dull and smothery, yet with little clear voices speaking up cheerfully out of it at intervals.',
    ]),
    _ch(7, '8Toad Hall', [
      'It was so very beautiful that the Mole could only hold up both paws and gasp, “O my! O my! O my!” The Rat brought the boat alongside the bank, made her fast, helped the still awkward Mole safely ashore, and swung out the luncheon-basket. The Mole begged as a favour to be allowed to unpack it all by himself; and the Rat was very pleased to indulge him, and to sprawl at full length on the grass and rest, while his excited friend shook out the table-cloth and spread it, took out all the mysterious packets one by one and arranged their contents in due order, still gasping, “O my! O my!” at each fresh revelation.',
      'When all was ready, the Rat said, “Now, pitch in, old fellow!” and the Mole was indeed very glad to obey, for he had started his spring-cleaning at a very early hour that morning, as people will do, and had not paused for bite or sup; and he had been through a very great deal since that distant time which now seemed so many days ago.',
      '“What are you looking at?” said the Rat presently, when the edge of their hunger was somewhat dulled, and the Mole’s eyes were able to wander off the table-cloth a little. “I am looking,” said the Mole, “at a streak of bubbles that I see travelling along the surface of the water. That is a thing that strikes me as funny.”',
      '“Bubbles? Oho!” said the Rat, and chirruped cheerily in an inviting sort of way. A streak of bubbles on the surface of the water showed him that someone was coming. A small black snout broke the water, and a head followed it. It was the Otter, dripping and cheerful, who clambered onto the bank and shook himself, scattering diamonds of spray.',
    ]),
    _ch(8, '9News of Toad', [
      '“Such a rumpus everywhere!” said the Otter. “All the world off pleasuring, and I such a waste of a morning! I came up this backwater to try and get a moment’s peace, and then stumble upon you fellows! At least—I beg pardon—I don’t exactly mean that, you know.”',
      'There was a rustle behind them, proceeding from a hedge wherein last year’s leaves still clung thick, and a stripy head, with high shoulders behind it, peered forth on them. “Come on, old Badger!” shouted the Rat. The Badger trotted forward a pace or two, then grunted, “H’m! Company,” and turned his back and disappeared from view. “That’s just the sort of fellow he is!” observed the disappointed Rat. “Simply hates Society! Now we shan’t see any more of him today.”',
      'The Otter, who had meanwhile been running his nose up and down the length of the boat, now sat down and remarked, “Toad’s been in again. Heard the news? He’s got a new craze. Always had crazes, of course. First it was boats, then it was caravans, now it’s motor-cars. He’ll smash himself up one of these days, if he isn’t careful.”',
      'The Rat nodded gloomily. “Toad’s rich, we all know; but he’s not a bit sensible. We were all very well when he was messing about with boats. Then came the caravan, all yellow and green, and he would have us go gipsying. Now it’s motor-cars, and nothing else will do. He has already been in hospital twice, and the last smash was a bad one. Something will have to be done.”',
    ]),
    _ch(9, '10The Open Road', [
      'It was a bright morning in the early part of summer; the river had resumed its wonted banks and its accustomed pace, and a hot sun seemed to be pulling everything green and bushy and spiky up out of the earth towards him, as if by strings. The Mole and the Water Rat had been up since dawn, very busy on matters connected with boats and the opening of the season.',
      'They were finishing breakfast in their little parlour and eagerly discussing their plans for the day, when a heavy knock sounded at the door. “Bother!” said the Rat, all over egg. “See who it is, Mole, like a good chap, since you’ve finished.” The Mole went to attend the summons, and the Rat heard him utter a cry of surprise. Then he flung the parlour door open and announced with much importance, “Mr. Toad!”',
      'The Toad, who was standing in the hall, came into the room, and stood there, looking the picture of happiness and good humour. “Hooray!” he cried, jumping up and down. “This is splendid!” He grasped the puzzled Rat by both paws. “I’ve done with caravans for good and all. I have discovered what is, I am convinced, the real thing at last. Come with me, dear Ratty, and old Mole, and you shall see.”',
      'He led them to the paddock, and there, drawn up in front of the stables, stood a shiny new motor-car, of immense size, painted a bright red, and complete with every modern convenience. The Toad walked slowly round it, looking it over with pride. “There you are!” he said. “Real life. The open road, the dusty highway, the heath, the common, the hedgerows, the rolling downs! Camps, villages, towns, cities! Here today, up and off to somewhere else tomorrow! Travel, change, interest, excitement! The whole world before you, and a horizon that’s always changing!”',
    ]),
    _ch(10, '11The Smash', [
      'The Rat looked very grave. “I don’t know that I think so much of that little song, Toad,” he observed. “You’re always in such a hurry. A motor-car poop-poops, and you lose your head. Last time you were in hospital for weeks.” “You don’t understand,” said the Toad. “Once you have known the joy of the open road in a motor-car, you can never go back.”',
      'They argued, they pleaded, they sat on his head, they told him he was a young fool. Toad only smiled a superior smile. At last they went with him, because a friend in trouble is a friend still, and because, if they did not go, he would certainly go alone and come to grief at once.',
      'The car started with a roar and a rush. Toad sat very upright, his goggles down, his smile enormous. For a mile or two all was well. Then a cart appeared round a bend. Toad took both hands off the wheel to wave. There was a frightful crash, a scattering of hens, a cloud of dust, and the motor-car lay on its side in the ditch, with Toad underneath a hedge, still smiling a happy smile.',
      '“You see?” said the Rat, picking him up. “This is what comes of it.” “What a run we had!” murmured Toad. “The poetry of motion! The real way to travel! The only way to travel! Here today—in next week tomorrow! Villages skipped, towns and cities jumped—always somebody else’s horizon! O bliss! O poop-poop! O my! O my!” They led him home very slowly, and put him to bed. He went on murmuring “Poop-poop!” till he fell asleep.',
    ]),
    _ch(11, '12Mr. Badger', [
      'The Mole had long wanted to make the acquaintance of the Badger, who seemed, by all accounts, to be such an important personage and, though rarely visible, to make his unseen influence felt by everybody about the place. But the Rat, whenever approached on the subject, always replied, with a smile, that Badger was a simply wonderful fellow, but that he couldn’t stand Society, and that he never came out, and that he hated callers.',
      '“That’s just the sort of fellow he is!” the Rat would say. “Goes to bed early, and gets up late, and never lets himself be seen. You can’t take him by surprise, either. If you call, he just doesn’t answer, and you may sit there as long as you like.”',
      'Winter came, and the Rat slept a good deal. The Mole, more restless, thought of the Wild Wood, and of Badger in the middle of it, and one afternoon, when the Rat was dozing in his armchair, the Mole slipped out, determined to pay a visit on his own account.',
      'It was a cold still afternoon with a hard steely sky overhead, when he slipped his arm into his overcoat, took down his stick, and set off, light-hearted and alert, for the Wild Wood. There was nothing to alarm him at first. Twigs crackled under his feet, logs tripped him, funguses on stumps resembled caricatures, and startled him for a moment, but that was all fun, and exciting.',
    ]),
    _ch(12, '13Lost in the Wood', [
      'It was already getting towards dusk when he reached the first fringe of trees and plunged without hesitation into the wood, looking anxiously on either side for Mr. Badger’s house. There was nothing to alarm him at first entry. Twigs crackled under his feet, logs tripped him, funguses on stumps looked like faces, but that was all fun.',
      'Then the faces began. Out of the corner of an eye he would see a face looking at him from a hole, then it would vanish. Hard-eyed little faces, wicked faces. Then the whistling began, thin and shrill. Then the pattering, as of little feet that followed and stopped when he stopped.',
      'He was alone, and far from help, and the night was closing in. He ran. He fell. He ran again. A hundred times he thought he saw a light, and a hundred times it was only a gleam on wet bark. At last, exhausted, he crept into the deep hollow of an old beech, covered himself with dry leaves, and lay there trembling, waiting for morning or for something worse.',
      'The Rat, waking from his nap and finding the Mole gone, knew at once where he had gone, and why. He took a stout stick, a pair of pistols, and a dark lantern, and set off for the Wild Wood without a moment’s delay. “Poor Mole,” he said. “I told him. I told him.”',
    ]),
    _ch(13, '14The Door-Scraper', [
      'It was some hours later that the Rat, after much searching and calling, heard a faint answering cry. He found the Mole in the hollow tree, very cold and very ashamed. “O Ratty!” he sobbed. “I’ve been so frightened. You were right, and I was a silly Mole.”',
      '“That’s all right,” said the Rat kindly. “But we can’t stay here. The snow has begun, and we must find shelter.” They struggled on through the thickening flakes. The Mole tripped over something hard, and sat down with a bump. “Oh, my leg!” he cried. “It’s a door-scraper!”',
      '“Don’t be funny, Mole,” said the Rat, rather sharply. “Who ever heard of a door-scraper in the middle of a wood?” “But it is,” said the Mole. “Look.” The Rat looked, and it was. Then they found a door-mat. Then, clearing the snow with their paws, they found a door. The Rat knocked.',
      'There was a long pause. Then a deep voice said, “Who is it this time, interrupting people on such a night? Speak up!” “It’s me, Rat, and my friend Mole, and we’ve lost our way in the snow, and we’re simply soaked.” There was the noise of a bolt shot back, and the Badger’s kind old face looked out. “What, Ratty, my dear little man! Come along in, both of you, at once. Why, you must be perished.”',
    ]),
    _ch(14, '15Badger’s Kitchen', [
      'The two cold, wet animals tumbled in. The Badger, who wore a long dressing-gown, carried a flat candlestick in his paw, and looked like some wise old hermit. He led them down a long, gloomy, and, to tell the truth, rather shabby passage, into a sort of central hall, out of which they could dimly see other long tunnel-like passages branching, passages mysterious and without apparent end.',
      'But there were fires in the rooms, and the passages were warm, and at last they came to the kitchen, where a great fire burnt on the hearth, and a kettle sang, and the table was laid for supper. The Badger’s house was just what it should have been, they both felt. It was not like the houses of the river-bank, all windows and little rooms; it was underground, and therefore safe, and therefore homelike.',
      'They dried themselves, and ate, and told their story. The Badger listened, nodding. “The Wild Wood is no place for a picnic,” he said. “You did right to come here. Tomorrow you shall go home, and I will see you through the wood myself.”',
      'After supper they sat by the fire, and the talk turned, as it always did among the river-bankers, to Toad. “We shall have to do something,” said the Badger. “Toad’s been arrested. Motor-car. Again. Cheek to a policeman. Fifteen years, they say. We must get him out, and we must make him a sensible Toad. When the time comes, we three will take him in hand.”',
    ]),
    _ch(15, '16Toad’s Adventures', [
      'Toad, meanwhile, sat in a dungeon, very sorry for himself, and not at all sorry for the policeman. He had been a conceited Toad, and now he was a miserable Toad, which was perhaps an improvement, though he did not think so. The days crawled. The gaoler’s daughter, who had a kind heart and a liking for animals, took pity on him, and brought him tea, and toast, and a little conversation.',
      '“Toad,” she said one evening, “you are very rich, they tell me, and used to palaces, and boats, and fine clothes. This is no life for you. I have a plan.” The plan was a washerwoman’s dress—her aunt’s—bonnet, shawl, and all. Toad, after much wounded pride, put it on. He looked, it must be admitted, a very plump and peculiar washerwoman, but the disguise served.',
      'He escaped. He tottered down the road, his heart beating. He came to a railway station, and, with a mixture of lies, tears, and the remains of his dignity, he got himself onto a train without a ticket. When the guard grew suspicious, Toad leapt from the moving train into the night, rolled down an embankment, and lay in the grass, breathless, free, and extremely dirty.',
      'A canal barge came next, and a barge-woman who was not easily deceived. When she found him out she tossed him into the canal. Toad swam, crawled out, stole the barge-horse, galloped away, and was thrown into a heap of leaves when the horse declined to be stolen any further. So, by water, rail, and mud, the Wet King of Toad Hall made his wretched way towards home.',
    ]),
    _ch(16, '17The Return', [
      'It was the Rat who found him at last, sitting on the river bank in the ruined washerwoman’s clothes, a melancholy figure against the sunset. “Toad,” said the Rat, “you are a disgrace. Come inside, get those things off, and don’t talk nonsense about being a hero. You have been a silly ass, and you are not out of the wood yet.”',
      'Toad, after a hot bath and a good meal, began to recover his conceit. He told the story of his escape with many additions, and was just getting to the most splendid part when the Mole and the Badger came in, looking very grave. “The Stoats and Weasels have taken Toad Hall,” said the Mole. “They are in there now, eating your stores, sleeping in your beds, and saying you will never come back.”',
      'Toad leapt up, purple. “I’ll have the law on them! I’ll—I’ll—” “You’ll sit down,” said the Badger, “and you’ll listen. We have a plan. There is a secret passage, known to your father and to me, that leads from the river into the butler’s pantry. Tonight we four will take sticks, and we will take them by surprise.”',
      'Toad wanted a speech, a banner, and a brass band. He was given a stick and a dark lantern, and told to keep quiet. He did not keep quiet, but they took him all the same, because a Toad, even a foolish Toad, has a right to fight for his own house.',
    ]),
    _ch(17, '18The Secret Passage', [
      'Night on the river was still and very dark. The four animals slipped into a boat and drifted down to a point below Toad Hall, where an old drain, half hidden by weeds, opened in the bank. The Badger went first, then the Rat, then the Mole, then Toad, who splashed and muttered until the Rat pinched him.',
      'The passage was long, low, and smelled of old earth and forgotten dinners. They crept, they crouched, they bumped their heads. At the far end the Badger stopped, and they heard, through a thin wall of panelling, the noise of a banquet—songs, thumping, the shrill voices of weasels, and the boast of a chief stoat that Toad was in prison forever and the Hall was theirs.',
      '“Now!” whispered the Badger. They burst through into the pantry, and from the pantry into the hall. What followed was not a long battle. The Wild Wooders had not expected four angry householders with sticks, and they had expected still less the particular fury of a Toad who saw strangers drinking his wine.',
      'Chairs went over, plates smashed, windows opened for hasty exits. In five minutes the Hall was itself again, very much broken, very much Toad’s, and full of a silence that smelled of spilled gravy and victory.',
    ]),
    _ch(18, '19The Banquet', [
      'Next day Toad wanted a triumph. He wanted posters, and a speech from the steps, and a song of his own composing, very long, with a chorus about how clever he was. The Badger said no. The Rat said no. The Mole, who was kinder, said that a modest banquet for friends would be enough.',
      'Toad sulked, then dressed himself with care, then sulked again, then, to everyone’s surprise, stood up at the dinner and made a short speech that was almost humble. He thanked his friends. He admitted, in a roundabout way, that motor-cars and boastfulness had not turned out as well as he had hoped. Then he sat down, very red, and ate a great deal of pudding.',
      'The river-bankers drank his health. The Badger, who did not like speeches, grunted that Toad would do. The Rat said there was hope for him yet. The Mole, looking round the repaired hall, thought that homes were worth the trouble they gave, and that friends were worth more than motor-cars, though he did not say so, because it would have sounded like a moral, and animals are shy of morals when the pudding is still on the table.',
      'Outside, the river went on with its old story, chuckling past the reeds. Toad Hall’s windows were lit. In the Wild Wood the remaining weasels went to bed earlier than usual, and dreamed, uneasily, of sticks.',
    ]),
    _ch(19, '20Dulce Domum', [
      'One December afternoon the Mole and the Rat were returning from a long ramble. The light was failing, and a thin sad rain was falling. Suddenly the Mole stopped, and a twitch came over him. He smelled his old home, the little house he had left so gaily in the spring, and had not thought of since.',
      '“Ratty!” he cried. “Come back! My home is near, and I must see it.” The Rat, who was thinking of supper and a fire, did not at first understand. Then he saw the Mole’s face, and he turned at once. They found the tunnel, and the little round door, and the dusty rooms, and the Mole stood in the middle of it all and wept, because it was small, and shabby, and his.',
      'They lit a fire. They found a tin or two, and some bottles, and they made a feast of sorts. Field-mice came carol-singing at the door, and were given coins and warm words. The Rat, who had thought a riverside house the only house worth having, sat very quiet, and was careful not to say that the ceiling was low.',
      'That night the Mole slept in his own bed. He knew he would go back to the river, and to boats, and to his friend. But he knew also that a fellow must have a place of his own to come to, even if he only comes to it once in a long while, when the year is old and the wind is in the willows.',
    ]),
    _ch(20, '21Wayfarers All', [
      'Summer waned. The Rat, sitting by the water, felt a restlessness he did not like to name. Southward the swallows gathered, talking of blue seas and old palaces of coral, and of the ships and the islands. The Rat listened, and his paws twitched.',
      'A Sea Rat came up the river, lean and travel-stained, with rings in his ears and stories in his mouth. He spoke of harbours, and spices, and the long wash of waves. The Water Rat, who had always said that the river was enough, rose as if in a dream and would have followed, stick in hand, towards the Wide World.',
      'The Mole found him in time. He did not argue about duty. He talked of the river as it was in the morning, and of the boat, and of the particular way the current took the bend by the weir. Little by little the glaze went out of the Rat’s eyes. He sat down. He took up a handful of dry grass and smelled it, as a man smells a letter from home.',
      '“I nearly went,” he said at last. “I know,” said the Mole. “That’s why I came.” They went back together, and the river received them without remark, which is the river’s way. The swallows left. The Rat stayed. Sometimes, on still evenings, he thought he heard the sea, very far off; then he picked up his sculls, and the sound went back to being only water against the bank.',
    ]),
    _ch(21, '22Piper at the Gates of Dawn', [
      'The Otter’s little son was missing. Searchers went up and down the backwaters. At night the Mole and the Rat took a boat and drifted, calling softly. The moon sank. A mist came over the meadows. Then, towards dawn, they heard music that was not of birds and not of men, and they saw, for a little while, something standing among the reeds that they had no name for, though they knew they were not afraid.',
      'The child was asleep at the feet of that presence, as if the night itself had kept him. When they looked again, there was only the river, and the first light, and a wind in the willows that might have been a sigh or a blessing. They took the little otter into the boat, and they did not speak of what they had seen, because some things will not bear talking of, and are none the worse for that.',
      'Behind them the sun came up, ordinary and kind. Ahead of them smoke rose from familiar chimneys. The Rat rowed, and the Mole held the child, and the world was itself again, which was, after all, what they had gone out to find.',
      'They restored the boy to his father, who said very little, being an otter, and felt a great deal. The searchers went home to breakfast. The river, which had known the whole of it, kept its counsel, as rivers do.',
    ]),
    _ch(22, '23Winter Talk', [
      'Snow sealed the Wild Wood. In Badger’s kitchen the four friends sat often, while the kettle talked and the tunnels of the house went off into darkness like thoughts one does not have to finish. They mended things. They told the same stories, which is the best use of old stories.',
      'Toad had not bought a motor-car. He had bought, it is true, a large book of maps, and had been seen looking at it with a moist eye; but the Badger had taken the book away and put it on a high shelf, and Toad had not yet found a ladder he was willing to admit he needed.',
      'The Mole learned to rest. The Rat made plans for the first day the ice should break. They were small plans—paint for the boat, a new painter, a picnic when the kingfishers came back—and they were enough. Outside, the wind went through the willows with a dry sound, like pages turned in a book nobody was reading because everybody already knew the words.',
      '“It has been a queer year,” said the Mole. “It has been a year,” said the Badger, which in his language was both agreement and a closing of the subject. They put more wood on the fire. Somewhere a mouse went along a passage, about its own important business. The house received it, as it received all small true things.',
    ]),
    _ch(23, '24Spring Again', [
      'When the ice went out of the river, it went in a hurry, as if ashamed of having stayed so long. Green came back in a night. The Rat was up before dawn, fussing over varnish. The Mole, who remembered another spring and a whitewash brush flung down in a tunnel, stood on the bank and laughed without quite knowing why.',
      'Toad appeared in a new waistcoat, very quiet for a Toad. He looked at the water and said, “There is a good deal to be said for staying at home.” Then he added, “Of course, if one had a really well-made boat—” The Rat said he might come as a passenger, if he kept his hands off the sculls. Toad, after a struggle visible on his face, agreed.',
      'They went downstream, past the weir, past the mill, past the backwater where a luncheon-basket had once seemed the whole of happiness. The Wild Wood lay dark on the left, but it was only a wood in daylight, and even the weasels, if they watched, kept their remarks to themselves.',
      'The wind moved in the willows, and the river told its long story again, the same story, which is never quite the same. The Mole listened, and thought of dust and whitewash, and of friends, and of how a fellow might leave his home in the morning and find, by evening, that the world had been waiting for him at the water’s edge all the time.',
    ]),
  ],
);
